spring.application.name=calificationsRest
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/crud_usuarios
db.host=localhost
db.port=3306
db.name=crud_usuarios
db.username=root
db.password=root

spring.session.store-type=none

smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=kgomezr2@unicartagena.edu.co
smtp.password=cpvjlrwqiojrpcas
smtp.from.address=kgomezr2@unicartagena.edu.co
smtp.from.name=Gestion de Usuarios

spring.aop.proxy-target-class=false
